###################################################################################################
#
# This github workflow implements integration tests which  validate that a newly introduced code
# change doesn't break existing code. Whenever the code base is changed this workflow  will be
# triggered
#
# Here are common examples of integration tests covered by this
# workflow:
#    - Run terraform validate to verify the syntax of the configuration file.
#    - Run terraform plan to ensure the configuration will work as expected.
#    - Static code analysis tools such as lint and format.
#
###################################################################################################

name: "kitchen mobile: PR Code review"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - "terraform/development/**"

jobs:
  # Code linting checking, validation and resources planning
  code-validation-dev:
    name: Code validation
    uses: filipefigueredo/pipeline-templates/.github/workflows/tf-cloud-code-validation.workflow.yaml@main
    with:
      target-directory: terraform/development
    secrets:
      terraform_cloud_api_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

  # Static analysis security scanning
  security-code-scanning:
    name: Security code scanning
    uses: filipefigueredo/pipeline-templates/.github/workflows/tfsec-code-scanning.workflow.yaml@main
