name: "Kitchen mobile: provisioning(bot)"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: choice
        options:
          - production
          - staging
          - test
          - dev
        default: dev

jobs:
  # Terraform provisioning
  infrastructure-provisioning:
    name: Infrastructure provisioning(${{ github.event.inputs.environment }})
    uses: nmbrs/reusable-workflows/.github/workflows/tf-cloud-provision.workflow.yaml@main
    with:
      target-directory: ${{ github.event.inputs.environment }}/kitchen-mobile
    secrets:
      terraform_cloud_api_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

  # Invoke application pipeline
  deploy-application:
    name: Deploy Payroll App(${{ github.event.inputs.environment }})
    needs: infrastructure-provisioning
    uses: nmbrs/reusable-workflows/.github/workflows/azure-devops-pipeline-triggering.workflow.yaml@main
    with:
      azure-devops-project-url: "https://dev.azure.com/nmbrs-projects/Payroll"
      azure-devops-pipeline-name: "Nmbrs.Code.Mobile.Kitchen - CD - Github"
      azure-devops-pipeline-variables: '{"App.Name": "mobile", "apptype.kitchen": "api,mobile,web,worker"}'
    secrets:
      azure-devops-access-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
