name: "Kitchen mobile: provisioning(push)"
on:
  push:
    branches: [main]
    paths:
      - dev/kitchen-mobile/**

jobs:
  # Terraform provisioning
  infrastructure-provisioning:
    name: Infrastructure provisioning(development)
    uses: nmbrs/reusable-workflows/.github/workflows/tf-cloud-provision.workflow.yaml@main
    with:
      target-directory: dev/kitchen-mobile
    secrets:
      terraform_cloud_api_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

  # Invoke application pipeline
  deploy-application:
    name: Deploy Payroll App(development)
    needs: infrastructure-provisioning
    uses: nmbrs/reusable-workflows/.github/workflows/azure-devops-pipeline-triggering.workflow.yaml@main
    with:
      azure-devops-project-url: "https://dev.azure.com/nmbrs-projects/Payroll"
      azure-devops-pipeline-name: "Nmbrs.Code.Mobile.Kitchen - CD - Github"
      azure-devops-pipeline-variables: '{"App.Name": "mobile", "apptype.kitchen": "api,mobile,web,worker"}'
    secrets:
      azure-devops-access-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
