name: "Kitchen mobile: teardown(bot)"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: choice
        options:
          - production
          - staging
          - test
          - dev
        default: dev
jobs:
  # Terraform teardown
  infrastructure-teardown:
    name: Infrastructure teardown(${{ github.event.inputs.environment }})
    uses:  nmbrs/reusable-workflows/.github/workflows/tf-cloud-teardown.workflow.yaml@main
    with:
      target-directory: ${{ github.event.inputs.environment }}/kitchen-mobile
    secrets:
      terraform_cloud_api_token: ${{ secrets.TF_CLOUD_API_TOKEN }}
