name: Scheduled Security Scanning

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '25 22,23,0 * * *'
jobs:
  # Static analysis security scanning
  security-code-scanning:
    name: Security code scanning
    uses: nmbrs/reusable-workflows/.github/workflows/tfsec-code-scanning.workflow.yaml@main
