---
name: 'sup-dog'
run-name: 'Sync "rg-${{ inputs.workload }}-${{ inputs.environment }}" permissions for "${{ inputs.environment }}"'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Azure environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
          - sand
      workload:
        description: "Azure Workload"
        required: true
        type: string
jobs:
  my_job:
    name: no thanks
    runs-on: ubuntu-22.04
    steps:
      - name: hey there
        run: |
          echo 'Sync "${{ inputs.environment }}" permissions for the resource group "rg-{{ inputs.workload }}-${{ inputs.environment }}'
