name: tf cloud provisioning
on:
  workflow_call:
    inputs:
      target-directory:
        description: "Target working directory"
        required: false
        type: string

    secrets:
      terraform_cloud_api_token:
        description: Terraform Cloud API token
        required: true

jobs:
  # Creates or updates infrastructure according to Terraform configuration files in the current directory.
  tf-apply:
    name: Terraform apply

    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: ./${{ inputs.target-directory }}

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Retrieves the terraform CLI used in the GitHub action workflow
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.terraform_cloud_api_token }}
          terraform_wrapper: true

      # Initializes terraform configurations.
      - name: Terraform Init
        id: init
        run: terraform init

      # Applies terraform configuration.
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
